apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  DATABASE_URL: postgresql://admin:fuad1234@postgres-service:5432/k8s-learning
  DATABASE_HOST: k8s-postgres:5432
  DATABASE_NAME: k8s-learning
